### ISSUE TITLE
Help: How to update KeyUpdate in TLS-Attacker  in Client Mode

### ISSUE THREAD

**Issue by skommula96** [tls-attacker/TLS-Attacker#107]
`echo 'K' |openssl s_client -connect 127.0.0.1:4433 -msg`

How to replicate this command in tls attacker in client mode
Any example ?
Thanks in advance

**Comment by skommula96** [comment]
any update?

**Comment by ic0ns** [comment]
So you want to send the message with the content "K"? You can just use the workflow_trace_type Full and set the defaultApplicationMessageData in the config to "K".

**Comment by ic0ns** [comment]
Ah I see K starts a keyupdate in openssl. Sorry. I don't think the current version supports KeyUpdates yet. We have it in the upcoming release.

**Comment by skommula96** [comment]
@ic0ns please provide some example how to send KeyUpdate in new release.

**Comment by mmaehren** [comment]
It should be possible to add it like any other message in a SendAction.
```
workflowTrace.addTlsAction(new SendAction(new KeyUpdateMessage(config)));
```
or in XML in the message list of a SendAction
```
<KeyUpdate>
  <requestUpdate>UPDATE_NOT_REQUESTED</requestUpdate>                         
</KeyUpdate>
```

**Comment by skommula96** [comment]
@mmaehren Thanks worked for me.
