### ISSUE TITLE
how to check 'verify return code' and 'verify return'  fields in TLS-Attacker

### ISSUE THREAD

**Issue by ghost** [tls-attacker/TLS-Attacker#108]
How to check these fields in TLS-Attacker:

```
Verification error: self signed certificate
Verify return code: 18 (self signed certificate)
Verify return code: 0 (ok)
verify return:1
```

**Comment by ic0ns** [comment]
TLS-Attacker does not evaluate the trust of certificates and just accepts whatever. If you want to check this you have to do it manually after
