### ISSUE TITLE
Tests are failing with release TLS-Attacker 3.7.0

### ISSUE THREAD

**Issue by ghost** [tls-attacker/TLS-Attacker#112]
some tests are failed  OpenJDK 11. 

please find the log
https://api.travis-ci.com/v3/job/513534564/log.txt

**Comment by ic0ns** [comment]
Java 11 is not officially supported yet. We are still working on that. The Problem ist that JAXB changed the formatting in Java 11, which causes our tests to fail...

**Comment by ic0ns** [comment]
Java11 is now supported wiht TLS-Attacker 3.8.0
