### ISSUE TITLE
Does TLS-Attacker Supports DTLS-1.3

### ISSUE THREAD

**Issue by skommula96** [tls-attacker/TLS-Attacker#114]

**Comment by ic0ns** [comment]
no. DTLS 1.3 is not fully specified yet so we currently do not support it. We plan to implement it once the first implementations appear.

**Comment by cameronelliott** [comment]
> no. DTLS 1.3 is not fully specified yet so we currently do not support it. We plan to implement it once the first implementations appear.

Thank you for making TLS Attacker.

Does this statement still apply? I see DTLS 1.3 was produced in April 22' 
https://www.rfc-editor.org/rfc/rfc9147.html

**Comment by ic0ns** [comment]
We are currently working on DTLS 1.3 support. I expext it to be completed internally in spring, and available to the public some time after that
