### ISSUE TITLE
new Help:How to replay a app message in one session?

### ISSUE THREAD

**Issue by dennisokko** [tls-attacker/TLS-Attacker#118]
How can i send the same message packet twice in a row?

**Comment by dennisokko** [comment]
I want to simulate a replay attack.
Use Java programming or XML

**Comment by dennisokko** [comment]
`Configurator.setAllLevels("", Level.INFO);
        Security.addProvider(new BouncyCastleProvider());

        Config config = Config.createConfig();
        config.setDefaultRunningMode(RunningModeType.CLIENT);
        OutboundConnection outboundConnection = config.getDefaultClientConnection();
        outboundConnection.setPort(Integer.parseInt(args[0]));
        config.setDefaultClientConnection(outboundConnection);
        config.setDefaultSelectedCipherSuite(CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256);
        config.setAddSessionTicketTLSExtension(true);

        WorkflowTrace trace = new WorkflowTrace();
        ClientHelloMessage clientHello = new ClientHelloMessage(config);
        MessageAction messageAction = MessageActionFactory.createAction(
                config, outboundConnection, ConnectionEndType.CLIENT, clientHello);
        trace.addTlsAction(messageAction);
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ServerHelloMessage(config),
                        new CertificateMessage(config),
                        new ECDHEServerKeyExchangeMessage(config),
                        new ServerHelloDoneMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.CLIENT,
                        new ECDHClientKeyExchangeMessage(config),
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        State state = new State(config, trace);
        WorkflowExecutor workflowExecutor =
                WorkflowExecutorFactory.createWorkflowExecutor(config.getWorkflowExecutorType(), state);
        workflowExecutor.executeWorkflow();

        System.out.println(clientHello.toString());
        System.out.println(ArrayConverter.bytesToHexString(state.getTlsContext().getClientRandom()));
        WorkflowTrace trace2 = new WorkflowTrace();
        SendAction sendaction = new SendAction(clientHello);
        sendaction.setRecords(messageAction.getRecords());
        trace2.addTlsAction(sendaction);
        trace2.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ServerHelloMessage(config),
                        new CertificateMessage(config),
                        new ECDHEServerKeyExchangeMessage(config),
                        new ServerHelloDoneMessage(config)));
        trace2.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.CLIENT,
                        new ECDHClientKeyExchangeMessage(config),
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        trace2.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));

        State state2 = new State(config, trace2);
        // state2.replaceTlsContext(state.getTlsContext());
        WorkflowExecutor workflowExecutor2 =
                WorkflowExecutorFactory.createWorkflowExecutor(config.getWorkflowExecutorType(), state2);
        workflowExecutor2.executeWorkflow();`

**Comment by dennisokko** [comment]
this is my code.
i want to handeshake first, and resend the client hello which had send at the first handshake in second handshake.

**Comment by ic0ns** [comment]
Do you want to replay the client hello encrypted or do you want to replay it plain?

**Comment by ic0ns** [comment]
Also - do you want to replay it as separate session (this is what you are doing now) or do you want to replay it in the same session?

**Comment by ic0ns** [comment]
Ok I think I get what you are trying to do now. You simply have to set: setUseFreshRandom(false) in the Config. That should do the trick

**Comment by dennisokko** [comment]
thank you very much

**Comment by dennisokko** [comment]
another question is: how can i resend a same app message packet in one session

**Comment by dennisokko** [comment]
Config config = Config.createConfig();
        config.setDefaultRunningMode(RunningModeType.CLIENT);
        OutboundConnection outboundConnection = config.getDefaultClientConnection();
        outboundConnection.setPort(Integer.parseInt(args[0]));
        config.setDefaultClientConnection(outboundConnection);
        config.setDefaultSelectedCipherSuite(CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256);
        config.setAddSessionTicketTLSExtension(true);

        WorkflowTrace trace = new WorkflowTrace();
        trace.addTlsAction(MessageActionFactory.createAction(
                config, outboundConnection, ConnectionEndType.CLIENT, new ClientHelloMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ServerHelloMessage(config),
                        new CertificateMessage(config),
                        new ECDHEServerKeyExchangeMessage(config),
                        new ServerHelloDoneMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.CLIENT,
                        new ECDHClientKeyExchangeMessage(config),
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        config.setUseFreshRandom(false);
        config.setUseAllProvidedRecords(true);
        ApplicationMessage app1 = new ApplicationMessage(config);
        MessageAction messageAction = MessageActionFactory.createAction(
                config,
                outboundConnection,
                ConnectionEndType.CLIENT,
                app1);
        trace.addTlsAction(messageAction);
        MessageAction messageAction2 = MessageActionFactory.createAction(
                config,
                outboundConnection,
                ConnectionEndType.CLIENT,
                app1);
        messageAction2.setMessages(messageAction.getMessages());
        messageAction2.setRecords(messageAction.getRecords());
        System.out.println(messageAction.getReadableString());
        trace.addTlsAction(messageAction2);
        State state = new State(config, trace);
        WorkflowExecutor workflowExecutor =
                WorkflowExecutorFactory.createWorkflowExecutor(config.getWorkflowExecutorType(), state);
        workflowExecutor.executeWorkflow();

**Comment by dennisokko** [comment]
I refer to this issue: https://github.com/tls-attacker/TLS-Attacker/issues/98, and Modify the code as follows.
But the following error is reported：

Exception in thread "main" de.rub.nds.tlsattacker.core.exceptions.ContextHandlingException: Cannot replace TlsContext because the new TlsContext defines another connection.
        at de.rub.nds.tlsattacker.core.state.ContextContainer.replaceTlsContext(ContextContainer.java:176)
        at de.rub.nds.tlsattacker.core.state.State.replaceTlsContext(State.java:166)
        at TLSS_TestSuite1_TestCase4_3a.main(TLSS_TestSuite1_TestCase4_3a.java:109)

**Comment by dennisokko** [comment]
Config config = Config.createConfig();
        config.setDefaultRunningMode(RunningModeType.CLIENT);
        OutboundConnection outboundConnection = config.getDefaultClientConnection();
        outboundConnection.setPort(Integer.parseInt(args[0]));
        config.setDefaultClientConnection(outboundConnection);
        config.setDefaultSelectedCipherSuite(CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256);
        config.setAddSessionTicketTLSExtension(true);

        de.rub.nds.tlsattacker.core.state.TlsContext ctx = new de.rub.nds.tlsattacker.core.state.TlsContext(config, outboundConnection);
        WorkflowTrace trace = new WorkflowTrace();
        trace.addTlsAction(MessageActionFactory.createAction(
                config, outboundConnection, ConnectionEndType.CLIENT, new ClientHelloMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ServerHelloMessage(config),
                        new CertificateMessage(config),
                        new ECDHEServerKeyExchangeMessage(config),
                        new ServerHelloDoneMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.CLIENT,
                        new ECDHClientKeyExchangeMessage(config),
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        config.setUseFreshRandom(false);
        config.setUseAllProvidedRecords(true);
        ApplicationMessage app1 = new ApplicationMessage(config);
        Chooser chooser = ChooserFactory.getChooser(ChooserType.DEFAULT, ctx, config);
        ApplicationMessagePreparator appPreparator = new ApplicationMessagePreparator(chooser, app1);
        appPreparator.prepare();
        MessageAction messageAction = MessageActionFactory.createAction(
                config,
                outboundConnection,
                ConnectionEndType.CLIENT,
                app1);
        trace.addTlsAction(messageAction);
        MessageAction messageAction2 = MessageActionFactory.createAction(
                config,
                outboundConnection,
                ConnectionEndType.CLIENT,
                app1);
        messageAction2.setMessages(messageAction.getMessages());
        messageAction2.setRecords(messageAction.getRecords());
        System.out.println(messageAction.getReadableString());
        trace.addTlsAction(messageAction2);
        State state = new State(config, trace);
        state.replaceTlsContext(ctx);
        WorkflowExecutor workflowExecutor =
                WorkflowExecutorFactory.createWorkflowExecutor(config.getWorkflowExecutorType(), state);
        workflowExecutor.executeWorkflow();
