### ISSUE TITLE
After receiving an unrelated TCP packet, TLS attacker sends the next message without waiting for the real expected message？

### ISSUE THREAD

**Issue by dennisokko** [tls-attacker/TLS-Attacker#119]
TLS attacker acts as the server. After sending the "server Hello done" message, it is expected to send the "change cipher spec" message after receiving the "client key exchange" and other messages sent by the client. However, when TLS attacker receives an unrelated TCP, it immediately sends the "change cipher spec" message without waiting for the real TLS message "client key exchange", How can I avoid this situation, such as setting the corresponding config.
![image](https://user-images.githubusercontent.com/54125561/144778776-0369655d-d0be-4990-a205-d267579f4a80.png)

**Comment by dennisokko** [comment]
![截图](https://user-images.githubusercontent.com/54125561/144779162-8e358a0d-346f-4d05-98ed-feb362b6c45d.JPG)

**Comment by ic0ns** [comment]
TLS-Attacker has different options on how to deal with "unexpected" messages. Generally, TLS-Attacker will wait a certain timeout - if that timeout is reached TLS-Attacker will stop receiving and move forward to the next action. If you think that the server will eventually answer, a simple fix is to just increase the timeout. If you do not want to continue with further actions and instead stop the execution you can set "earlyStop" to true in the config.

**Comment by dennisokko** [comment]
> TLS-Attacker has different options on how to deal with "unexpected" messages. Generally, TLS-Attacker will wait a certain timeout - if that timeout is reached TLS-Attacker will stop receiving and move forward to the next action. If you think that the server will eventually answer, a simple fix is to just increase the timeout. If you do not want to continue with further actions and instead stop the execution you can set "earlyStop" to true in the config.

how can i increase the timeout?which config?

**Comment by ic0ns** [comment]
For example with -timeout 5000 you set the timeout to 5 seconds. With the flag -config you can pass a Config to TLS-Attacker as an XML document. Take a look here where I explain this: https://web-in-security.blogspot.com/2019/03/playing-with-tls-attacker.html
