### ISSUE TITLE
how can i resend a same app message packet in one session.

### ISSUE THREAD

**Issue by ghost** [tls-attacker/TLS-Attacker#120]
this is my code, i try to use the firse message's message and records to replay the second one, but before execution, it is null.

**Comment by dennisokko** [comment]
Config config = Config.createConfig();
        config.setDefaultRunningMode(RunningModeType.CLIENT);
        OutboundConnection outboundConnection = config.getDefaultClientConnection();
        outboundConnection.setPort(Integer.parseInt(args[0]));
        config.setDefaultClientConnection(outboundConnection);
        config.setDefaultSelectedCipherSuite(CipherSuite.TLS_ECDHE_RSA_WITH_AES_128_GCM_SHA256);
        config.setAddSessionTicketTLSExtension(true);

        WorkflowTrace trace = new WorkflowTrace();
        trace.addTlsAction(MessageActionFactory.createAction(
                config, outboundConnection, ConnectionEndType.CLIENT, new ClientHelloMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ServerHelloMessage(config),
                        new CertificateMessage(config),
                        new ECDHEServerKeyExchangeMessage(config),
                        new ServerHelloDoneMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.CLIENT,
                        new ECDHClientKeyExchangeMessage(config),
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        trace.addTlsAction(
                MessageActionFactory.createAction(
                        config,
                        outboundConnection,
                        ConnectionEndType.SERVER,
                        new ChangeCipherSpecMessage(config),
                        new FinishedMessage(config)));
        config.setUseFreshRandom(false);
        config.setUseAllProvidedRecords(true);
        ApplicationMessage app1 = new ApplicationMessage(config);
        MessageAction messageAction = MessageActionFactory.createAction(
                config,
                outboundConnection,
                ConnectionEndType.CLIENT,
                app1);
        trace.addTlsAction(messageAction);
        MessageAction messageAction2 = MessageActionFactory.createAction(
                config,
                outboundConnection,
                ConnectionEndType.CLIENT,
                app1);
        messageAction2.setMessages(messageAction.getMessages());
        messageAction2.setRecords(messageAction.getRecords());
        System.out.println(messageAction.getReadableString());
        trace.addTlsAction(messageAction2);
        State state = new State(config, trace);
        WorkflowExecutor workflowExecutor =
                WorkflowExecutorFactory.createWorkflowExecutor(config.getWorkflowExecutorType(), state);
        workflowExecutor.executeWorkflow();

**Comment by ic0ns** [comment]
Sorry for the late response. I kind of missed this issue. The reason why its null is because all values are computed at runtime. So before executing the trace you cannot access the message. To perform this test you can either put a duplicate modification on the record, or if you need more control, set TLS-Attacker in the config to not close the transport handler and then manually send the message after execution (or add a custom action).
