### ISSUE TITLE
Newest version in Maven central

### ISSUE THREAD

**Issue by kostis** [tls-attacker/TLS-Attacker#149]
I saw that there is a new version (5.1.6) released.
Congratulations!

Are there any plans to also include this release in the Maven central repository?
It seems that the [latest version posted there is 3.8.1](https://mvnrepository.com/artifact/de.rub.nds.tlsattacker/TLS-Attacker) which is quite old by now.

Also, minor nitpick:
The [README](https://github.com/tls-attacker/TLS-Attacker/blob/master/README.md) promises that
> If you want to use this project as a dependency, you do not have to compile it yourself and can include it in your pom .xml as follows. ...  <Code showing version 4.0.0>

AFAIK, there is no such version.  It would be a good idea to keep this updated to the latest version posted on the Maven repo.

**Comment by mmaehren** [comment]
Hey,

starting with version 4.0, we switched from de.rub.nds.**tlsattacker** to de.rub.nds.**tls.attacker**. Newer versions, including 5.1.6, have been published under this new group id.

**Comment by mmaehren** [comment]
Thank you for reporting this.
The readme.md has been update with release v5.2.1.
