### ISSUE TITLE
Can't get expected result.

### ISSUE THREAD

**Issue by ora-sun** [tls-attacker/TLS-Attacker#150]
My TLS-Attacker version is 5.1.6. I use TLS-Attacker as a client to connect to an openssl server whose version is openssl1.0.1f. I modify the WorkflowTrace according to [https://web-in-security.blogspot.com/2019/03/playing-with-tls-attacker.html]() and the concrete xml file (trace.xml)  is shown below.

<workflowTrace>

    <Send>
        <messages>
            <ServerHello/>
        </messages>
    </Send>
    <Receive>
        <expectedMessages>
            <ServerHello/>
            <Certificate/>
            <ServerHelloDone/>
        </expectedMessages>
    </Receive>
</workflowTrace>

I use openssl to set up TLS service, and then I run TLS-Attacker as a client. The expected result shown in the blog is like this 
![result](https://user-images.githubusercontent.com/92298719/231699082-056496c5-7859-4015-81f2-79867a44f77c.jpg)
But I haven't got the same consequence. 
The server:
![server](https://user-images.githubusercontent.com/92298719/231698987-e074443a-263e-43d0-a239-779298a877c8.jpg)
The client:
![client](https://user-images.githubusercontent.com/92298719/231698687-51f4d0dc-881e-40a0-9dfd-74ca8bf41aed.jpg)
So I want to ask for help about the reason and what I should yo do .Thank you!

**Comment by ic0ns** [comment]
You are sending a ServerHello message not a ClientHello message, this is why the server is (rightfully) complaining. ClientHello and ServerHello are two different messages in TLS.
