### ISSUE TITLE
How to construct a TLS Record with empty content?

### ISSUE THREAD

**Issue by lh0xf** [tls-attacker/TLS-Attacker#154]
I want to construct some empty TLS messages (like EmptyClientHello, EmptyChangeCipherSpec) to test if the TLS implementations handles them correctly.
Also, I want to achieve this through xml files. Below are my codes.
~~~xml
<workflowTrace>
    <Send>
        <messages>
        </messages>
        <records>
            <Record>
                <contentType>
                    <ByteExplicitValueModification>
                        <explicitValue>22</explicitValue>
                    </ByteExplicitValueModification>
                </contentType>
                <length>
                    <IntegerExplicitValueModification>
                        <explicitValue>0</explicitValue>
                    </IntegerExplicitValueModification>
                </length>
            </Record>
        </records>
    </Send>
</workflowTrace>
~~~

Does it work ? Thanks for any help.

**Comment by ic0ns** [comment]
On which version of TLS-Attacker are you? We recently had bigger changes around this, I want to make sure that the solution will work for you.

**Comment by lh0xf** [comment]
TLS-Attacker 3.7.3

**Comment by JonSnowWhite** [comment]
Sorry for the late reply. Is this relevant, and if yes for which TLS-Attacker version? Your example works for newer versions!
