### ISSUE TITLE
Installing Issue

### ISSUE THREAD

**Issue by PR0J3CT12** [tls-attacker/TLS-Attacker#157]
Hello everyone! I'm trying to install tls-attacker following the documentation but getting error on TLS-Core installation:
DefaultChooserTest.setUp:37 » UnsupportedOperation This public key is not supported:null

Tried on different OS's - same thing. How can i fix it?

**Comment by ic0ns** [comment]
Without any further details I would guess that this is related to the java version. TLS-Attacker runs on java 11.

**Comment by GKnirps** [comment]
A colleague of mine hat the same problem with TLS-Scanner. In that case, the tip with the version helped. He switched from Java 20 to Java 11 and it worked.
