### ISSUE TITLE
Regarding the Current State of Fuzz

### ISSUE THREAD

**Issue by y1174804262** [tls-attacker/TLS-Attacker#165]
Dear esteemed Mr. Robert, I happened to come across your response from 2019 stating that you were in the process of developing a more powerful TLS-fuzz tool. May I humbly ask if the new tool you referred to is TLS-Anvil? Or perhaps your esteemed team is still in the state of development. If it wouldn't be too much trouble, I would deeply appreciate any guidance or insights you could provide regarding research approaches to TLS security. I recognize that this might be a presumptuous request and I hope you don't find it impolite. Thank you sincerely for your time and consideration.

**Comment by ic0ns** [comment]
Hey,
oh, jeah fuzzing - it is still not publicly available yet. The paper is ready since 7 years but in a constant review cycle where we submit it now and then. The plan was to release the tool when the paper get accepted. We have to internally decide if we just release it at some point/eprint.

**Comment by y1174804262** [comment]
Wow! It is with great anticipation that I look forward to this. It is my sincerest hope that your academic paper receives swift acceptance. I hold the belief that the tool developed by your esteemed team is set to cause a stir. I shall pivot my research thinking in response to this. Thank you most cordially for your enlightening response! It is with genuineness that I extend my wishes for the earliest acceptance of your paper.
