### ISSUE TITLE
Need all the XML keyword for each SSL and DTLS protocol messages

### ISSUE THREAD

**Issue by sajualways** [tls-attacker/TLS-Attacker#169]
Hi,

Is there some link where I can get all the XML name entities for each of the supported messages of SSL and DTLS protocol

**Comment by ic0ns** [comment]
Yes, you can find the syntax for everything in the WorkflowTrace in our xsd (https://[github.com/tls-attacker/TLS-Attacker/blob/main/resources/schema/workflowTrace.xsd)](url)
for the Config you can find them here:
[https://github.com/tls-attacker/TLS-Attacker/blob/main/resources/schema/Config.xsd](https://github.com/tls-attacker/TLS-Attacker/blob/main/resources/schema/Config.xsd)
