### ISSUE TITLE
Behavior Change in Workflow Execution with Combined ReceiveAction

### ISSUE THREAD

**Issue by hamma96** [tls-attacker/TLS-Attacker#174]
**Title: Workflow Execution Issue with `ReceiveAction` in TLS-Attacker**

**Description:**

I am encountering an issue with the TLS-Attacker library where the workflow execution does not work as expected depending on how `ReceiveAction` is used. Specifically, handling them as separate actions does not work, whereas combining multiple messages into a single `ReceiveAction` does.

#### Non-Working Case
```java
Config config = Config.createConfig();
WorkflowTrace trace = new WorkflowTrace();
trace.addTlsAction(new SendAction(new ClientHelloMessage()));
trace.addTlsAction(new ReceiveAction(new ServerHelloMessage()));
trace.addTlsAction(new ReceiveAction(new ServerHelloDoneMessage()));
State state = new State(config, trace);
DefaultWorkflowExecutor executor = new DefaultWorkflowExecutor(state);
executor.executeWorkflow();
```

#### Working Case
```java
Config config = Config.createConfig();
WorkflowTrace trace = new WorkflowTrace();
trace.addTlsAction(new SendAction(new ClientHelloMessage()));
trace.addTlsAction(new ReceiveAction(new ServerHelloMessage(), new ServerHelloDoneMessage()));
State state = new State(config, trace);
DefaultWorkflowExecutor executor = new DefaultWorkflowExecutor(state);
executor.executeWorkflow();
```

### Observations:
- **Non-Working Case**: Handling `ServerHelloMessage` and `ServerHelloDoneMessage` as separate `ReceiveAction` objects  does not execute the workflow correctly.
- **Working Case**: Combining `ServerHelloMessage` and `ServerHelloDoneMessage` into a single `ReceiveAction` works as expected.

I will attach a screenshot from the PCAP file that illustrates the discrepancy.

### Questions:
1. **Behavior Change**: Why does combining multiple messages into a single `ReceiveAction` cause the workflow to work? Is this a known issue or a limitation within the library?
2. **Best Practice**: Should `ReceiveAction` be used with one message per action to ensure correct workflow execution, or is there a recommended approach for combining messages?

I would appreciate any guidance or recommendations on how to address this issue. If further details are needed, please let me know.

**Attachments:**
![image](https://github.com/user-attachments/assets/4c9a68ca-8692-42d5-abd3-e00398dc9a65)

Thank you!

---

**Comment by ic0ns** [comment]
This is the expected behavior. Your workflow trace is effectively your plan. A receive action (in the default configuration) tries to receive the messages you specified up to a specified timeout. In your case, the receive action sees the SH, which it expected, but then also sees that there is more data to receive and also processes that which causes your "plan" to fail. For the second action, there is then nothing to be received anymore then.

For most applications this behavior more useful. For example, if you want to receive a ClientHello, but the client sent a ClientHello and an Alert message you want to know about the Alert message right away.

**Comment by hamma96** [comment]
Hi @ic0ns,

Thank you for the explanation; it makes sense that the `ReceiveAction` will process any incoming messages that it finds, causing the second action to fail when nothing is left to receive. This behavior definitely seems useful for real-world scenarios where we would want to process all available messages, especially in the case of unexpected alerts or additional messages in the handshake.

However, I do have a few follow-up questions to better understand how to work with this behavior and possibly adapt my tests accordingly:

1. **Handling Multi-Message Reception**: 
   In cases like mine, where I want to structure the reception into multiple `ReceiveAction`s (e.g., first `ServerHello`, then `ServerHelloDone`), what is the recommended approach? Should I configure a custom timeout for each `ReceiveAction` to avoid receiving extra messages, or is there a built-in way to handle partial message reception within the same `ReceiveAction`?

2. **Timeout and Message Fragmentation**: 
   Is there any recommended strategy for balancing the timeout and expected message flow? In certain scenarios where messages may arrive separately (e.g., due to fragmentation), would extending the timeout for individual `ReceiveAction`s be a better approach?

3. **Receive Action for Strict Message Sequence**: 
   Is there a configuration or mechanism in TLS-Attacker to enforce strict message sequencing within `ReceiveAction`s? In cases where I want to ensure that specific messages arrive exactly when expected (and no others), can I adjust the `ReceiveAction` to enforce this?

4. **Best Practices**: 
   For users who are testing complex handshakes and want to model the trace closely, are there any best practices for avoiding failures when there are unexpected or extra messages received during a `ReceiveAction`? Should I always anticipate additional messages when configuring these actions?

Thanks again for your time and help. I’m looking forward to your advice on best approaches for structuring workflow traces to ensure that complex handshakes and edge cases can be tested accurately!

**Comment by ic0ns** [comment]
1) I don't see why you would want two receive actions here. What's your use case for this? Ideally, you would merge them into one.

2) Usually, you just set a timeout to a reasonably high value and then put all the expected messages in the receive action. If the action receives all expected messages you do not need to wait the full timeout. If you want to abort on unexpected messages you can play with features like: stopTraceAfterUnexpected in the config. Fragmentation does not change TLS-Attacker's behavior.

3) Strict is the default. If you want non-strict behavior you need to set the message as not required: https://github.com/tls-attacker/TLS-Attacker/blob/5fe4faf6e06e4422c20b01c3f756c7bc7cf1d0b8/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol/ProtocolMessage.java#L119

4) The best practice is to always be as strict as possible with your plan and to avoid ambiguous plans where possible. Additionally, avoid running into the timeout. Use GenericReceive actions only when you do not know what the peer will respond with.

**Comment by ic0ns** [comment]
to me, this looks like the decryption failed. This can happen if we have the wrong keys - then we decrypt something non-sensical which we then cant parse which then again trips us off since the length fields are not correct anymore. TLS-Attacker will per default try to decrypt messages even if the Tag or HMAC verification failed.

**Comment by hamma96** [comment]
Hi @ic0ns , you are right, I provided the right key and now the flow is working as expected. Thank you for your support, I will close this issue now
