### ISSUE TITLE
TLS protocol version is set to 1.2 even when using 1.3 config

### ISSUE THREAD

**Issue by tobiasbayer** [tls-attacker/TLS-Attacker#175]
I am trying to establish a TLS 1.3 connection via the client library in my Java/Kotlin code.
From https://github.com/tls-attacker/TLS-Attacker/issues/76 I understood that I've to load a valid TLS 1.3 configuration which I did via 
```
Config.createConfig(this::class.java.getClassLoader().getResourceAsStream("clientConfig/tls13.config"))
```

with the contents of https://github.com/tls-attacker/TLS-Attacker/blob/main/resources/configs/tls13.config

But my CLIENT_HELLO message still points to TLS 1.2. I think the culprit is `CoreClientHelloPreparator`:

```
private void prepareProtocolVersion(T msg) {
        if (chooser.getConfig().getHighestProtocolVersion().isTLS13()) {
            msg.setProtocolVersion(ProtocolVersion.TLS12.getValue());
        } else {
            msg.setProtocolVersion(chooser.getConfig().getHighestProtocolVersion().getValue());
        }
        LOGGER.debug(
                "ProtocolVersion: "
                        + ArrayConverter.bytesToHexString(msg.getProtocolVersion().getValue()));
    }
```

Why does it fall back to TLS12 when TLS13 is the highest protocol version in the config? What would I have to do to get TLS13 in the CLIENT_HELLO message?

**Comment by ic0ns** [comment]
this is because of RFC8446. They deprecated the version field in the client hello in TLS 1.3 and hardcode it to TLS 1.2. The "true" version is then sent in a Protocol version extension.

**Comment by ic0ns** [comment]
So this behavior is actually what you are supposed to do in TLS 1.3 :confounded: . If you want to overwrite this with a different version field (to create a malformed message) you need to apply a modification to the field.

**Comment by tobiasbayer** [comment]
I see. Got confused when debugging an issue and looking at the CLIENT_HELLO. I thought the "wrong" version to be the root cause of the other issue.
Thanks a lot!
