### ISSUE TITLE
Build Error TLS-Attacker v.6.1.4

### ISSUE THREAD

**Issue by GSoJC234** [tls-attacker/TLS-Attacker#176]
Hello,

I’m researching TLS protocol implementation bugs using your TLS-Attacker tools, which are excellent for building and processing TLS protocol messages.

I’m trying to build TLS-Attacker v6.1.4, but I’m having trouble finding de.rub.nds.asn1-attacker:jar:3.0.0 and de.rub.nds.tls.attacker:transport:jar:6.1.4. 

I have noticed that the ASN.1-Attacker repository hasn't been updated, but it still supports version 2.0.0.

Could you please update the ASN.1-Attacker repository? 
Alternatively, 
is there another way for me to obtain de.rub.nds.asn1-attacker:jar:3.0.0 and de.rub.nds.tls.attacker:transport:jar:6.1.4

Thank you for your excellent release!

**Comment by mmaehren** [comment]
Oh sorry, we forgot to release the ASN.1-Attacker dependency. I just pushed the 3.0.0 version to the public GitHub repo and maven central.

**Comment by GSoJC234** [comment]
Thank you!
I've just successfully built TLS-Attacker v6.1.4, and I'm really impressed with the supported features and revised code structure in this version.

Thanks for updating TLS-Attacker!
