### ISSUE TITLE
Question concerning workflow serialisation

### ISSUE THREAD

**Issue by SidolFreiburg** [tls-attacker/TLS-Attacker#186]
Hello TLS-Attacker team,

we have a question concerning the WorkflowTraceSerializer. We wrote some tests on top of the TLS-Core functionality and up to version 5.1.3 it was possible to serialise the workflow trace using this function:

`WorkflowTraceSerializer.write(path.toFile(), state.getWorkflowTrace());`

With Version 6.1.7 we get the following error:

Caused by: com.sun.istack.SAXException2: Marshalling von Typ "de.rub.nds.x509attacker.x509.model.DirectoryString" als Element ist nicht möglich, weil er diesem Kontext nicht bekannt ist
	at org.glassfish.jaxb.runtime.v2.runtime.XMLSerializer.reportError(XMLSerializer.java:213)
	at org.glassfish.jaxb.runtime.v2.runtime.ClassBeanInfoImpl.serializeRoot(ClassBeanInfoImpl.java:311)

If we understand it right, this happens if a certificate is to be serialised. 

We tried a fix in the WorkflowTraceSerializer by adding the following code to the getJAXBContext() function

```
Set<Class<? extends Asn1Encodable>> asn1Stuff =
    reflections.getSubTypesOf(Asn1Encodable.class);
classes.addAll(asn1Stuff);
```
Unfortunately, this lead to another error:

org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException: 6 counts of IllegalAnnotationExceptions
de.rub.nds.x509attacker.x509.model.X509Component ist eine Schnittstelle, und JAXB kann keine Schnittstellen verarbeiten.
	this problem is related to the following location:
		at de.rub.nds.x509attacker.x509.model.X509Component
de.rub.nds.asn1.model.Asn1Encodable ist eine Schnittstelle, und JAXB kann keine Schnittstellen verarbeiten.
	this problem is related to the following location:
		at de.rub.nds.asn1.model.Asn1Encodable
		at private de.rub.nds.asn1.model.Asn1Encodable de.rub.nds.x509attacker.x509.model.extensions.PolicyQualifierInfo.qualifier
		at de.rub.nds.x509attacker.x509.model.extensions.PolicyQualifierInfo
de.rub.nds.asn1.time.TimeField ist eine Schnittstelle, und JAXB kann keine Schnittstellen verarbeiten.
	this problem is related to the following location:
		at de.rub.nds.asn1.time.TimeField
de.rub.nds.x509attacker.x509.model.X509ExplicitComponent ist eine Schnittstelle, und JAXB kann keine Schnittstellen verarbeiten.
	this problem is related to the following location:
		at de.rub.nds.x509attacker.x509.model.X509ExplicitComponent
de.rub.nds.x509attacker.x509.model.publickey.parameters.PublicParameters ist eine Schnittstelle, und JAXB kann keine Schnittstellen verarbeiten.
	this problem is related to the following location:
		at de.rub.nds.x509attacker.x509.model.publickey.parameters.PublicParameters
Ungültige @XmlElementRef: Typ "class de.rub.nds.x509attacker.x509.model.GeneralName" oder eine seiner Unterklassen sind in diesem Kontext nicht bekannt.
	this problem is related to the following location:
		at private java.util.List de.rub.nds.x509attacker.x509.model.extensions.GeneralNames.generalName
		at de.rub.nds.x509attacker.x509.model.extensions.GeneralNames
		at private de.rub.nds.x509attacker.x509.model.extensions.GeneralNames de.rub.nds.x509attacker.x509.model.extensions.DistributionPoint.crlIssuer
		at de.rub.nds.x509attacker.x509.model.extensions.DistributionPoint
		at private java.util.List de.rub.nds.x509attacker.x509.model.extensions.CrlDistributionPoints.distributionPoint
		at de.rub.nds.x509attacker.x509.model.extensions.CrlDistributionPoints

Another approach would be to add all classes manually, like `classes.add(DirectoryString.class);`, but we wanted to ask whether  there  is a more generic approach?

**Comment by ic0ns** [comment]
We recently faced the same issue and fixed it in the upcoming version like this:
```

    public static synchronized JAXBContext getJAXBContext() throws JAXBException, IOException {
        if (context == null) {
            // TODO we could do this scanning during building and then just collect the
            // results
            // TODO it would also be good if we didn't have to hardcode the package name
            // here, but I could not get it work without it. Hours wasted: 3
            String packageName = "de.rub";
            Reflections reflections =
                    new Reflections(
                            new ConfigurationBuilder()
                                    .setUrls(ClasspathHelper.forPackage(packageName))
                                    .filterInputsBy(
                                            new FilterBuilder().includePackage(packageName)));
            Set<Class<?>> classes = new HashSet<>();
            classes.add(WorkflowTrace.class);
            classes.addAll(getSerializableSubTypes(reflections, TlsAction.class));
            classes.addAll(getSerializableSubTypes(reflections, DataContainer.class));
            classes.addAll(getSerializableSubTypes(reflections, Asn1Encodable.class));
            classes.addAll(getSerializableSubTypes(reflections, PublicKeyContent.class));
            classes.addAll(getSerializableSubTypes(reflections, SignatureComputations.class));

            LOGGER.trace("Registering Classes in JAXBContext of WorkflowTraceSerializer:");
            for (Class<?> tempClass : classes) {
                LOGGER.trace(tempClass.getName());
            }
            context = JAXBContext.newInstance(classes.toArray(new Class[classes.size()]));
        }
        return context;
    }
```
Does that solve it for you?

**Comment by SidolFreiburg** [comment]
Thank you for the fast response. Unfortunately, we see a different error now:

java.lang.RuntimeException: org.glassfish.jaxb.runtime.v2.runtime.IllegalAnnotationsException: 2 counts of IllegalAnnotationExceptions
de.rub.nds.asn1.model.Asn1Encodable ist eine Schnittstelle, und JAXB kann keine Schnittstellen verarbeiten.
	this problem is related to the following location:
		at de.rub.nds.asn1.model.Asn1Encodable
		at private de.rub.nds.asn1.model.Asn1Encodable de.rub.nds.x509attacker.x509.model.extensions.PolicyQualifierInfo.qualifier
		at de.rub.nds.x509attacker.x509.model.extensions.PolicyQualifierInfo
		at private java.util.List de.rub.nds.x509attacker.x509.model.extensions.PolicyQualifiers.policyQualifierInfo
		at de.rub.nds.x509attacker.x509.model.extensions.PolicyQualifiers
Ungültige @XmlElementRef: Typ "class de.rub.nds.x509attacker.x509.model.GeneralName" oder eine seiner Unterklassen sind in diesem Kontext nicht bekannt.
	this problem is related to the following location:
		at private java.util.List de.rub.nds.x509attacker.x509.model.extensions.GeneralNames.generalName
		at de.rub.nds.x509attacker.x509.model.extensions.GeneralNames
		at private de.rub.nds.x509attacker.x509.model.extensions.GeneralNames de.rub.nds.x509attacker.x509.model.extensions.AuthorityKeyIdentifier.authorityCertIssuer
		at de.rub.nds.x509attacker.x509.model.extensions.AuthorityKeyIdentifier

We are using version 3.1.2 of the X509-Attacker and Version 3.0.0 of the ASN1-Attacker.

**Comment by ic0ns** [comment]
@mmaehren is this fully fixed in the dev repo? Can we make a new release?

**Comment by mmaehren** [comment]
All of these _should_ be fixed. I made a new release for our latest tagged version.

**Comment by SidolFreiburg** [comment]
Hello! Thank you very much for the update. We'll try it out shortly. Good to see that the X509 context update was also fixed because we were also investigating on that matter.

**Comment by SidolFreiburg** [comment]
Thanks again, the WorkflowTraceSerializer works now!
