### ISSUE TITLE
SupportedVersionsExtension Message Handler Error

### ISSUE THREAD

**Issue by GSoJC234** [tls-attacker/TLS-Attacker#187]
Hi,  

In TLS 1.3, the `SupportedVersionsExtension` is used by both the client and server.  

When the server receives a `ClientHello` message containing this extension, it calls the [`SupportedVersionsExtensionHandler`](https://github.com/tls-attacker/TLS-Attacker/blob/06f86b8d56fa7e0e48821e4f37575d406041963c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol/handler/extension/SupportedVersionsExtensionHandler.java#L26), which correctly sets the client's supported protocol versions. Similarly, when the client receives a `ServerHello` message, the handler is called to set the selected protocol version.  

This behavior seems fine during the receiving phase, but I’ve noticed issues during the sending phase for both `ClientHello` and `ServerHello` messages:  

1. **When the client sends a `ClientHello` message with the `SupportedVersionsExtension`**:  
   The handler sets the selected protocol version instead of the client’s supported protocol versions. This happens because the `talkingConnectionEndType` is set to `SERVER`, which seems inconsistent.  

2. **When the server sends a `ServerHello` message with the `SupportedVersionsExtension`**:  
   The handler sets the client’s supported protocol versions instead of the selected protocol version.  

This raises the following questions:  

- Is it incorrect to call handlers during the sending phase of messages with extensions?  
- If this is indeed incorrect, how should the sender’s context handle and store the message-specific information in the `TlsContext` object?  

Additionally, I believe the same issue exists for the [`KeyShareExtensionMessageHandler`](https://github.com/tls-attacker/TLS-Attacker/blob/06f86b8d56fa7e0e48821e4f37575d406041963c/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/protocol/handler/extension/KeyShareExtensionHandler.java#L28).  
- For example, when the client sends a `ClientHello` message with a `KeyShareExtension`, the public key needs to be stored in the `TlsContext` to compute the `handshakeTrafficSecret`. This implies that the handler for the `KeyShareExtensionMessage` should be called during the sending phase as well.  

Am I missing something here, or is there a misunderstanding in my interpretation of how extension handlers should behave?  

Thank you for your help and clarification!

**Comment by ic0ns** [comment]
Hey,
handlers are called during sending and receiving of messages. Their job is to move the message contents to the context such that future messages can depend on them.
To me this looks like in your case the talking connection end type is not changed in the context. This is usually done in the layer stack automatically upon and send or receive. Do you have a custom setup that somehow does not call this? If so, when you change direction you have to adjust the talking direction.

**Comment by GSoJC234** [comment]
You are absolutely right!

I have a custom setup that, for some reason, does not automatically set the connection end type. However, after manually setting the connection end type, all the issues were resolved.

Thank you!
