### ISSUE TITLE
How to rewrite TLS-Attacker to makes it possible to support more Cipher Suite?

### ISSUE THREAD

**Issue by Alice47962** [tls-attacker/TLS-Attacker#71]
Hello developers, I want to ask about how to rewrite TLS-Attacker to makes it possible to support more Cipher Suite? 
Thank you!

**Comment by ic0ns** [comment]
Which cipher suites are you missing? It depends on the exact cipher suite you want to implement on what you have to do.

**Comment by Alice47962** [comment]
> Which cipher suites are you missing? It depends on the exact cipher suite you want to implement on what you have to do.

I want to use cipher suite TLS_RSA_WITH_SM4_CBC_SHA256 to achieve a complete handshake.

**Comment by ic0ns** [comment]
Oh cool! I always wanted to add the chinese cipher suites :)
It depends, I assume. Is it possible to get an instance of SM4 like this:
```
IvParameterSpec encryptIv = new IvParameterSpec(iv);
cipher = Cipher.getInstance(algorithm.getJavaName());
cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(key,algorithm.getJavaName()), encryptIv);
```
Or do you need a custom class to perform encryption and decryption? Besides SM4 does the cipher suite do anything special on the record layer?

**Comment by Alice47962** [comment]
> Oh cool! I always wanted to add the chinese cipher suites :)
> It depends, I assume. Is it possible to get an instance of SM4 like this:
> 
> ```
> IvParameterSpec encryptIv = new IvParameterSpec(iv);
> cipher = Cipher.getInstance(algorithm.getJavaName());
> cipher.init(Cipher.ENCRYPT_MODE, new SecretKeySpec(key,algorithm.getJavaName()), encryptIv);
> ```
> 
> Or do you need a custom class to perform encryption and decryption? Besides SM4 does the cipher suite do anything special on the record layer?

I don't think I need custom class, and the cipher suite will not do anything special on the record layer. 
I just need to perform a different encryption algorithm, now I want to ask how TLS-Attacker implement different cipher suite. This may be helpful for me to extend cipher suite?

**Comment by ic0ns** [comment]
Ok, if that is the case, then you can simply add the cipher suite to the following classes:

CipherAlgorithm.java # here you define the general properties of the cipher

CipherSuite.java. # here you define the cipher suite, also add it to the "implemented" list

BulkCipherAlgorithm.java # Here you just need to add SM4 & add SM4 to the getBulkCipherAlgorithm() function

AlgorithmResolver.getCipher() # Here you define which cipher suites should use SM4

After that you should be done if I did not miss a spot.

**Comment by Alice47962** [comment]
> Ok, if that is the case, then you can simply add the cipher suite to the following classes:
> 
> CipherAlgorithm.java # here you define the general properties of the cipher
> 
> CipherSuite.java. # here you define the cipher suite, also add it to the "implemented" list
> 
> BulkCipherAlgorithm.java # Here you just need to add SM4 & add SM4 to the getBulkCipherAlgorithm() function
> 
> AlgorithmResolver.getCipher() # Here you define which cipher suites should use SM4
> 
> After that you should be done if I did not miss a spot.

Thank you very much for your help. I will try it as soon as possible.

**Comment by ic0ns** [comment]
If you need help or get stuck just let me know. I really wanted to add these cipher suites - but I do not speak chinese, which makes it a lot more complicated :)

**Comment by Alice47962** [comment]
> If you need help or get stuck just let me know. I really wanted to add these cipher suites - but I do not speak chinese, which makes it a lot more complicated :)

If I meet problem or make progress, I'll keep you posted :)

**Comment by drwetter** [comment]
> I want to use cipher suite TLS_RSA_WITH_SM4_CBC_SHA256 to achieve a complete handshake.

Is that somehow official? Latest info I found was the draft expired 2 years ago. And that wasn't even the same cipher (https://tools.ietf.org/id/draft-sca-curdle-tls-sm34-00.html#rfc.section.3, hash function SM3 instead of SHA256)

Interestingly there are proposal for TLS 1.3 ciphers: https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-03

<\/OT>

**Comment by Alice47962** [comment]
> > I want to use cipher suite TLS_RSA_WITH_SM4_CBC_SHA256 to achieve a complete handshake.
> 
> Is that somehow official? Latest info I found was the draft expired 2 years ago. And that wasn't even the same cipher (https://tools.ietf.org/id/draft-sca-curdle-tls-sm34-00.html#rfc.section.3, hash function SM3 instead of SHA256)
> 
> Interestingly there are proposal for TLS 1.3 ciphers: https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-03
> 
> </OT>

China's 《information security technology CTLs protocol (Draft for comments)》proposes this cipher suite, which you can find on page 16 of this document: https://www.tc260.org.cn/file/2018-01-18/593fd08a-b333-4398-b888-f2a70f39aeb7.doc . But this document is in Chinese.

**Comment by Alice47962** [comment]
> > > I want to use cipher suite TLS_RSA_WITH_SM4_CBC_SHA256 to achieve a complete handshake.
> > 
> > 
> > Is that somehow official? Latest info I found was the draft expired 2 years ago. And that wasn't even the same cipher (https://tools.ietf.org/id/draft-sca-curdle-tls-sm34-00.html#rfc.section.3, hash function SM3 instead of SHA256)
> > Interestingly there are proposal for TLS 1.3 ciphers: https://tools.ietf.org/html/draft-yang-tls-tls13-sm-suites-03
> 
> China's 《information security technology CTLs protocol (Draft for comments)》proposes this cipher suite, which you can find on page 16 of this document: https://www.tc260.org.cn/file/2018-01-18/593fd08a-b333-4398-b888-f2a70f39aeb7.doc . But this document is in Chinese.

This may not be the official TLS standard at present. I just want to do some safety testing.

**Comment by drwetter** [comment]
Thank you! 

I'll see how far I can get when I paste the content into a translation engine. (BTW: the doc contained macros, sigh)

PS: I am not involved in this project, I was just curious about the cipher suites.

**Comment by Alice47962** [comment]
> Ok, if that is the case, then you can simply add the cipher suite to the following classes:
> 
> CipherAlgorithm.java # here you define the general properties of the cipher
> 
> CipherSuite.java. # here you define the cipher suite, also add it to the "implemented" list
> 
> BulkCipherAlgorithm.java # Here you just need to add SM4 & add SM4 to the getBulkCipherAlgorithm() function
> 
> AlgorithmResolver.getCipher() # Here you define which cipher suites should use SM4
> 
> After that you should be done if I did not miss a spot.

Hello developer, I have found the files you mentioned, but I can't find which file to encrypt and decrypt the message after reading the cipher suite.

**Comment by ic0ns** [comment]
This is done in the RecordEncryptor/RecordDecryptor classes, as well as in the "RecordBlockCipher" (for CBC). Optimally you will not need to touch those.

**Comment by Alice47962** [comment]
> This is done in the RecordEncryptor/RecordDecryptor classes, as well as in the "RecordBlockCipher" (for CBC). Optimally you will not need to touch those.

Thank you for your help.

**Comment by Alice47962** [comment]
> This is done in the RecordEncryptor/RecordDecryptor classes, as well as in the "RecordBlockCipher" (for CBC). Optimally you will not need to touch those.

Hello developer, I have added the cipher suite I said before in TLS attacker. But not yet tested. Now I want to check and analyze the security of the cipher suite. I haven't found a tutorial on the Internet, so I want to ask you about this problem. Thank you.

**Comment by ic0ns** [comment]
Well, what exactly do you want to analyze?

**Comment by Alice47962** [comment]
> Well, what exactly do you want to analyze?

I want to check the security and compliance of TLS password implementation.

**Comment by ic0ns** [comment]
I'm sorry, what do you mean with "TLS password implementation" ? TLS-Attacker is a low level tool which allows you to perform tests in the TLS-Handshake manually, or to develop tools which perform these handshakes for you. It does not contain a testsuite, but you can certainly build one with it.

**Comment by Alice47962** [comment]
> I'm sorry, what do you mean with "TLS password implementation" ? TLS-Attacker is a low level tool which allows you to perform tests in the TLS-Handshake manually, or to develop tools which perform these handshakes for you. It does not contain a testsuite, but you can certainly build one with it.

Thank you. I'll take a closer look.

**Comment by Alice47962** [comment]
> I'm sorry, what do you mean with "TLS password implementation" ? TLS-Attacker is a low level tool which allows you to perform tests in the TLS-Handshake manually, or to develop tools which perform these handshakes for you. It does not contain a testsuite, but you can certainly build one with it.

Hello developer, because I want to add Chinese Password Suite to TLS attacker, I need to use the certificate issued by Chinese password algorithm, but I can't find where to define the certificate verification. I only found how to get the key pair in the chooseCertificateKeyPair function in the CertificateByteChooser.java file.

**Comment by ic0ns** [comment]
TLS-Attacker currently does not verify Certificates at all. It just accepts whatever is within the Certificate and uses that as a public key.

**Comment by Alice47962** [comment]
> TLS-Attacker currently does not verify Certificates at all. It just accepts whatever is within the Certificate and uses that as a public key.

Thank you very much!!

**Comment by Alice47962** [comment]
> TLS-Attacker currently does not verify Certificates at all. It just accepts whatever is within the Certificate and uses that as a public key.

Hello developer, sorry to disturb you again. I'd like to ask which code TLS attacker uses to parse the information from the other server? Because I want to find the certificate from the server, so I can extract the public key in the certificate (Java library cannot extract the public key of the certificate I want, I need to overwrite here).

**Comment by ic0ns** [comment]
Sorry I think I didnt see that you responded here again. You have to look into the CertificateHandler class for this.
