### ISSUE TITLE
How to differentiate between TCP and UDP transport while sending SSL or DTLS messages

### ISSUE THREAD

**Issue by sajualways** [tls-attacker/TLS-Attacker#79]
i see that both TCP and udp contains same Send and Receive tags in workflow trace

<Send>
<Receive>

How to differentiate between two in a workflow trace ?

**Comment by ic0ns** [comment]
I am not sure what you mean. But if you want to switch from TCP to UDP you need to specify a transport_handler_type == UDP

**Comment by sajualways** [comment]
I meant inside XML file, how to differentiate between TCP and UDP messages ?

**Comment by ic0ns** [comment]
Sorry for the late response. You can define this inside of the Config within the defaultConnection. For reference checkout: https://github.com/tls-attacker/TLS-Attacker/blob/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/config/delegate/TransportHandlerDelegate.java

If you want to specific this inside of a WorkflowTrace you have to define an explicit connection, and attach your actions to that connection:

```
    <InboundConnection>
        <alias>tcpclient2mitm</alias>
        <port>2222</port>
        <transportHandlerType>TCP</transportHandlerType>
    </InboundConnection>
    <OutboundConnection>
        <alias>mitm2udpserver</alias>
        <port>4444</port>
        <hostname>localhost</hostname>
        <transportHandlerType>UDP</transportHandlerType>
    </OutboundConnection>
    <Receive>
        <connectionAlias>tcpclient2mitm</connectionAlias>
        <expectedMessages/>
    </Receive>
    <Send>
        <connectionAlias>mitm2udpserver</connectionAlias>
        <messages>
            <ClientHello/>
        </messages>
    </Send>
```

The reason why this is rather "confusion" is that TLS-Attacker also supports workflows with more than 2 parties for man in the middle scenarios. You therefor need to define for each connection individually whether it uses UDP/TCP to allow for potential TLS/DTLS cross protocol attacks. If you just want one connection you can simply define one connection (whether its a server or client(inbound, outbound) and assign the actions to it. The simpler way is through the default connection though (in the Config).
