### ISSUE TITLE
Can TLS-Attacker3.0B send application data to and from the server?

### ISSUE THREAD

**Issue by Alice47962** [tls-attacker/TLS-Attacker#80]
Hello, developer, I would like to ask can TLS-Attacker3.0B send application data to and from the server? I found in the code of a configuration parameter, called: workflowExecutorShouldOpen. This parameter defaults to true so TLS-Attacker closes the connection after receiving a finished message from the server. But I tried to change the value of this parameter to False but the link was still closed after all the code was executed. How could I make TLS-Attacker send and receive application data from the server? Thank you.

**Comment by ic0ns** [comment]
Hey,
yes it can. The flag you are talking about is not the correct flag. The flag you want is: "workflowExecutorShouldClose". The flag means that the WorkflowExecutor, which is internally responsible for the execution of a workflow trace, will not close the underlying socket on its own. If you want to send messages via code you should just set the flag, and afterwards you can use the connection as you want (for example by using it with this class here: https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/socket/TlsAttackerSocket.java ).

**Comment by Alice47962** [comment]
> Hey,
> yes it can. The flag you are talking about is not the correct flag. The flag you want is: "workflowExecutorShouldClose". The flag means that the WorkflowExecutor, which is internally responsible for the execution of a workflow trace, will not close the underlying socket on its own. If you want to send messages via code you should just set the flag, and afterwards you can use the connection as you want (for example by using it with this class here: https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/socket/TlsAttackerSocket.java ).

I'm sorry I misspelled the name of the flag when I asked the question, but I don't seem to understand you. Are you saying that setting this flag as “flase” will enable sending messages to each other with the server? I tried to set the value of this flag to “false”, but after all code execution, the link is still closed. Is there something wrong with my operation?

**Comment by ic0ns** [comment]
Are you running a custom TLS-Attacker application or are you running the default TLS-Server?

**Comment by Alice47962** [comment]
> Are you running a custom TLS-Attacker application or are you running the default TLS-Server?

I used the default TLS-Client as the Client to try to connect to the openssl server.

**Comment by ic0ns** [comment]
Ah ok, I think I see where the misunderstandig is. TLS-Attacker does not have an interactive shell nor does it read data from stdin. If you want to send application data with the provided TLS-Client.jar or TLS-Server.jar you have to add a Send action to you worklflow trace with the appropriate application data message. For example:
```
<Send>
	<messages>
		<Application>
			<dataConfig>414141414141</dataConfig> <!-- Sends AAAAAA -->
		</Application>
	</messages>
</Send>
```

**Comment by Alice47962** [comment]
> Ah ok, I think I see where the misunderstandig is. TLS-Attacker does not have an interactive shell nor does it read data from stdin. If you want to send application data with the provided TLS-Client.jar or TLS-Server.jar you have to add a Send action to you worklflow trace with the appropriate application data message. For example:
> 
> ```
> <Send>
> 	<messages>
> 		<Application>
> 			<dataConfig>414141414141</dataConfig> 
> 		</Application>
> 	</messages>
> </Send>
> ```

I understand. Thank you very much for your patient answer.
