### ISSUE TITLE
Am I able to use the ciphers and extensions in an SSLsocket in an httpclient/httprequest

### ISSUE THREAD

**Issue by bayanrasooly** [tls-attacker/TLS-Attacker#81]
I was wondering if I could use the vast list available here for my httpclient, is it doable?

I am using the default java.net.http client. Thank you!

**Comment by ic0ns** [comment]
Hey,
probably not without writing some code. We have a TlsAttackerSocket class (https://github.com/RUB-NDS/TLS-Attacker/blob/master/TLS-Core/src/main/java/de/rub/nds/tlsattacker/core/socket/TlsAttackerSocket.java) which is using TLS-Attacker for something which works similiar as a normal java socket (although on a slightly different interface). You will probably have to write something similar which works with the interface you are using. 

But please note: TLS-Attacker code does not provide ANY security. It does not check signatures, it does not check macs or AEAD tags and is using static and predictable secrets. Do not use this code to build anything that is transmitting any data of value and do not trust any data that is tramsmitted through TLS-Attacker.
