### ISSUE TITLE
Help: I want to set Length in Record Layer in Client hello

### ISSUE THREAD

**Issue by ayushbindlish** [tls-attacker/TLS-Attacker#96]
How can I set length in record layer in client hello message?

TLSv1.2 Record Layer: Handshake Protocol: Client Hello
    Content Type: Handshake (22)
    Version: TLS 1.2 (0x0303)
    **Length: 824**
    Handshake Protocol: Client Hello

I want to change the Length variable here without fragmenting the packet.

**Comment by ic0ns** [comment]
This is the same as #97
